Master Project/Assets/Scripts.meta
Master Project/Assets/Scripts/Cooking.meta
Master Project/Assets/Scripts/Dating.meta
Master Project/Assets/Scripts/General.meta

Close #10 -- Test issue assigned to Noah, sorry if you were using this, I'll leave the branch open for now.

Merging into Master

---

CONTRIBUTING.md

Added the artist naming convention rules to the CONTRIBUTING.md

Artist Naming Rules

---

.gitattributes
Art/Animations/Hudson_AnimationGDDoc.gif
Art/Animations/Hudson_AnimationGDDoc.mov
Art/Illustrator/MazurInGameUI.ai
Art/Illustrator/MazurMainMenuUI.ai
Art/PNG_s/Chinese Vampire.png
Art/PNG_s/FOOD LAYOUT.png
Art/PNG_s/Gargolye.png
Art/PNG_s/Hudson_CerbConcepts.png
Art/PNG_s/MazurUxUiFonts.png
Art/PNG_s/MazurUxUiMenus.png
Art/PNG_s/Phillips_Slime_1.png
Art/PNG_s/Pizarro-Ruiz_Dodomeki.png
Art/PNG_s/Pizarro-Ruiz_Interior Concept.png
Art/PNG_s/harvest.png
Art/PSD_s/Chinese Vampire.psd
Art/PSD_s/FOOD LAYOUT.psd
Art/PSD_s/Gargolye.psd
Art/PSD_s/Hudson_CerbConcepts.psd
Art/PSD_s/MazurUxUiFonts.psd
Art/PSD_s/MazurUxUiMenus.psd
Art/PSD_s/Phillips_Slime_1.psd
Art/PSD_s/Pizarro-Ruiz_Dodomeki.psd
Art/PSD_s/Pizarro-Ruiz_Interior Concept.psd
Art/PSD_s/harvest full body.psd.psd
Art/PSD_s/harvest.psd

Marino art updates

---

Art/Bright_Assets/Char sheet.sai2
Art/Bright_Assets/NewCanvas1tyryu6u6u.sai2
Art/Bright_Assets/harvest faces.png
Art/Bright_Assets/harvest faces.psd
Art/Bright_Assets/harvest full body.png
Art/Bright_Assets/harvest full body.psd.psd
Art/Bright_Assets/harvest.png
Art/Bright_Assets/harvest.psd
Art/Bright_Assets/her fece.sai2

Added preexisting assets

---

Art/Mazur_Assets/Illustrator/MazurBattleUI.ai
Art/Mazur_Assets/Illustrator/MazurInGameUI.ai
Art/Mazur_Assets/Illustrator/MazurMainMenuUI.ai
Art/Mazur_Assets/PNG/MazurBattleUI-01.png
Art/Mazur_Assets/PNG/MazurBattleUIGuide.png
Art/Mazur_Assets/PNG/MazurUxUiFonts.png
Art/Mazur_Assets/PNG/MazurUxUiMenus.png
Art/Mazur_Assets/PNG/MazurWheresWolf.png
Art/Mazur_Assets/PSD/MazurUxUiFonts.psd
Art/Mazur_Assets/PSD/MazurUxUiMenus.psd
Art/Mazur_Assets/PSD/MazurWheresWolf.psd

Mazur Art Upload1

---

Art/Mazur_Assets/Illustrator/MazurDialogueUI.ai
Art/Mazur_Assets/Illustrator/MazurMainMenuLayout.ai
Art/Mazur_Assets/PNG/MazurBattleUIArt-01.png
Art/Mazur_Assets/PNG/MazurCreditsMenu-01.png
Art/Mazur_Assets/PNG/MazurDialogueUI-01.png
Art/Mazur_Assets/PNG/MazurDialogueUIArt-01.png
Art/Mazur_Assets/PNG/MazurDialogueUIGuide-01.png
Art/Mazur_Assets/PNG/MazurInGameUIGuide.png
Art/Mazur_Assets/PNG/MazurIngameUI.png
Art/Mazur_Assets/PNG/MazurInstructionsMenu-01-01.png
Art/Mazur_Assets/PNG/MazurMainMenuArt-01.png
Art/Mazur_Assets/PNG/MazurMainMenuLayout-01.png
Art/Mazur_Assets/PNG/MazurOptionsMenu-01.png

Mazur art upload

---

Art/Pizarro-Ruiz_Assets/Pizarro-Ruiz_Cutting Board BG.psd
Art/Pizarro-Ruiz_Assets/Pizarro-Ruiz_Fight BG.psd
Art/Pizarro-Ruiz_Assets/Pizarro-Ruiz_Grill BG.psd
Art/Pizarro-Ruiz_Assets/Pizarro-Ruiz_Microwave BG.psd
Art/Pizarro-Ruiz_Assets/Pizarro-Ruiz_Mixing BG.psd
Art/Pizarro-Ruiz_Assets/Pizarro-Ruiz_Shake n Bake.psd

Background Concepts for week 2 close #49

Pizarro backgrounds

---

Art/Mazur_Assets/Illustrator/Mazur_Battle_UI_2.ai
Art/Mazur_Assets/Illustrator/Mazur_Dialogue_UI_2.ai
Art/Mazur_Assets/Illustrator/Mazur_MainMenu_UI_2.ai
Art/Mazur_Assets/PNG/Mazur_Battle_UI_2.png
Art/Mazur_Assets/PNG/Mazur_Battle_UI_2_Guide.png
Art/Mazur_Assets/PNG/Mazur_Battle_UI_Art_2.png
Art/Mazur_Assets/PNG/Mazur_Dialogue_UI_2.png
Art/Mazur_Assets/PNG/Mazur_Dialogue_UI_Art_2.png
Art/Mazur_Assets/PNG/Mazur_Dialogue_UI_Guide_2.png
Art/Mazur_Assets/PNG/Mazur_Options_Menu_2.png

The battle and dialogue UI has been reduced in size and adjusted for mechanics.

Updated Battle/Dialogue UI and Options Menu

---

Art/UXUI/Illustrator/Mazur_Tutorial_UI_1.ai
Art/UXUI/PNG/Tutorial/Mazur_Chopping_Cut.png
Art/UXUI/PNG/Tutorial/Mazur_Chopping_Knife.png
Art/UXUI/PNG/Tutorial/Mazur_Chopping_Uncut.png
Art/UXUI/PNG/Tutorial/Mazur_Microwave_Button.png
Art/UXUI/PNG/Tutorial/Mazur_Microwave_Button_Pressed.png
Art/UXUI/PNG/Tutorial/Mazur_Microwave_Countdown_0.png
Art/UXUI/PNG/Tutorial/Mazur_Microwave_Countdown_1.png
Art/UXUI/PNG/Tutorial/Mazur_Microwave_Countdown_2.png
Art/UXUI/PNG/Tutorial/Mazur_Microwave_Countdown_3.png
Art/UXUI/PNG/Tutorial/Mazur_Microwave_Stop_Text.png
Art/UXUI/PNG/Tutorial/Mazur_Shaker.png
Art/UXUI/PNG/Tutorial/Mazur_Spacebar.png
Art/UXUI/PNG/Tutorial/Mazur_Spacebar_Pressed.png
Art/UXUI/PNG/Tutorial/Mazur_Tutorial_Mouse_Icon.png

Chopping, Shake, and Microwave tutorial UI
There should be 14 PNGs and 1 AI file.

Tutorial UI

---

Art/Sound/Getting to Know You.mp3
Art/Sound/Getting to Know You.mscz
Art/Sound/Soulfood.mp3
Art/Sound/Soulfood.mscz

Added music files

---

Master Project/Assets/Scenes/Shaking.meta
Master Project/Assets/Scenes/Shaking/Main Scene.unity
Master Project/Assets/Scenes/Shaking/Main Scene.unity.meta
Master Project/Assets/Scenes/Shaking/Shaker.cs
Master Project/Assets/Scenes/Shaking/Shaker.cs.meta
Master Project/Assets/Scenes/Shaking/Shaking Scripts.meta
Master Project/Assets/Scenes/Shaking/Shaking Scripts/ShakerScript.cs
Master Project/Assets/Scenes/Shaking/Shaking Scripts/ShakerScript.cs.meta
Master Project/Assets/Scenes/Shaking/Shaking.unity
Master Project/Assets/Scenes/Shaking/Shaking.unity.meta
Master Project/Assets/Scenes/Shaking/Square.png
Master Project/Assets/Scenes/Shaking/Square.png.meta

added shaking scene and corresponding scripts

added shaking scene

---

Master Project/Assets/Scenes/Combat/Scripts.meta
Master Project/Assets/Scenes/Dialogue/DialogueScene.unity
Master Project/Assets/Scenes/Grill/Assets.meta

I swapped around the anchors for the dialogue scene so it looks nicer in 16:9. Current fix for #97.

Dialogue marino

---

Master Project/Assets/Scripts/Monsters.meta
Master Project/Assets/Scripts/Monsters/MonsterData.cs
Master Project/Assets/Scripts/Monsters/MonsterData.cs.meta

This is just a barebones implementation. I'll be able to add the rest shortly after.

MonsterData loading V1

---

Master Project/Assets/Scenes/Main Menu.meta
Master Project/Assets/Scenes/Main Menu/Main Menu.unity
Master Project/Assets/Scenes/Main Menu/Main Menu.unity.meta
Master Project/Assets/Scenes/Main Menu/Scripts.meta
Master Project/Assets/Scenes/Main Menu/Scripts/PlayOnclick.cs
Master Project/Assets/Scenes/Main Menu/Scripts/PlayOnclick.cs.meta

added main menu

---

Master Project/Assets/Scenes/Combat/CombatScene.unity
Master Project/Assets/Scenes/Combat/Qi_Scripts/BegHandler.cs
Master Project/Assets/Scenes/Combat/Qi_Scripts/BegHandler.cs.meta
Master Project/Assets/Scenes/Combat/Qi_Scripts/CouponHandler.cs
Master Project/Assets/Scenes/Combat/Qi_Scripts/FlatterHandler.cs
Master Project/Assets/Scenes/Combat/Qi_Scripts/FreeFoodHandler.cs
Master Project/Assets/Scenes/Combat/Qi_Scripts/Heal.cs
Master Project/Assets/Scenes/Combat/Qi_Scripts/HealthBar.cs
Master Project/Assets/Scenes/Combat/Qi_Scripts/HealthBar.cs.meta
Master Project/Assets/Scenes/Combat/Qi_Scripts/ManagerBar.cs
Master Project/Assets/Scenes/Combat/Qi_Scripts/MonsterAction.cs
Master Project/Assets/Scenes/Combat/Qi_Scripts/OfferDrinkHandler.cs
Master Project/Assets/Scenes/Combat/Qi_Scripts/Reason.cs
Master Project/Assets/Scenes/Combat/Qi_Scripts/Reason.cs.meta
Master Project/Assets/Scenes/Combat/Qi_Scripts/Talk.cs
Master Project/UnityPackageManager/manifest.json

Add health bar and manager bar controller. Defined the amount of manager bar decreased based on the Monster type as well as talk options.

BattleScene

---

Art/UXUI/Illustrator/Mazur_Tutorial_UI_2.ai
Art/UXUI/PNG/Tutorial/Mazur_Grill_1.png
Art/UXUI/PNG/Tutorial/Mazur_Grill_Cooked_1.png
Art/UXUI/PNG/Tutorial/Mazur_Grill_Uncooked_1.png
Art/UXUI/PNG/Tutorial/Mazur_Spatula_1.png
Art/UXUI/PNG/Tutorial/Mazur_Spoon_1.png
Art/UXUI/PNG/Tutorial/Mazur_Stir_Bowl_Back_1.png
Art/UXUI/PNG/Tutorial/Mazur_Stir_Bowl_Front_1.png
Art/UXUI/PNG/Tutorial/Mazur_Stir_Bowl_Liquid_1.png

Grill: Grill, Cooked Meat, Uncooked Meat, Spatula
Stirring: Spoon, Front of Bowl, Liquid, Back of Bowl

Tutorial Assets 2

---

Art/Backgrounds/Editor_Files/Pizarro-Ruiz_IngredientSelection_3.psd
Art/Backgrounds/PNGs/Pizarro-Ruiz_IngredientSelection_3.png
Art/Backgrounds/PNGs/Pizarro-Ruiz_ShakenBake_2.png

Finished ingredient selection screen close #116

Pizarro background revisions

---

Art/Sound/Cerberus is Barkin For Battle.mp3
Art/Sound/ReDacted Unleashes V O I D Pitch Shifted.mp3

Redact. Cerb. Battle Tracks

---

Art/Sound/Nessie Drowns Out the Competition.mp3

Nessie Battle Track

---

Art/Animations/Editor_Files/RECOVER_Hudson_MicrowaveMASTER_2.fla
Art/Animations/Editor_Files/RECOVER_Hudson_MicrowaveOpen_2.fla
Art/Animations/User_Files/Sprite Sheets/Hudson_MicrowaveOpenSPRITE_1.png

Opening, Closed (Off) and Closed (On)
Other sequences will be following this one shortly in one pull request.

Microwave Sprite Sheet

---

Art/Monsters/Editor_Files/Pizarro-Ruiz_NessieBattleSketch1.psd
Art/Monsters/Editor_Files/Pizarro-Ruiz_NessieSpriteSketches1.psd

Nessie Sketches

---

Art/Davis_Qave Art Folder/Davis_CabinetFoods_1.psd
Art/Davis_Qave Art Folder/Davis_CabinetFoods_3.png
Art/Davis_Qave Art Folder/Davis_CabinetFoods_3.psd
Art/Davis_Qave Art Folder/Davis_Food_Layout_2.psd
Art/Davis_Qave Art Folder/Davis_Ingredients_2.png
Art/Davis_Qave Art Folder/Davis_Ingredients_2.psd
Art/Davis_Qave Art Folder/Davis_LakeBedShake_1.psd
Art/Davis_Qave Art Folder/Davis_Tool_Layout_2.psd
Art/Davis_Qave Art Folder/Knife_Asset_1.png
Art/Davis_Qave Art Folder/Knife_Asset_1.psd
Art/PNG_s/AquariumGravel_1.png
Art/PNG_s/CannedBean_1.png
Art/PNG_s/CannedMeat_1.png
Art/PNG_s/Cheese_1.png
Art/PNG_s/CrushedSouls_1.png
Art/PNG_s/GroundBeef.png
Art/PNG_s/IceCream_1.png
Art/PNG_s/Knife_!.png
Art/PNG_s/Onion.png
Art/PNG_s/Pepper_1.png
Art/PNG_s/WhipCream_1.png

Davis food ingredients

---

Master Project/Assets/Scenes/Microwave/Scripts/Microwave.cs
Master Project/Assets/Scenes/Microwave/Scripts/MicrowaveTimerScript.cs

fixed timer formatting, merging small change before getting scorekeeper changes to implement scoring @noahwillcrow @gmarino2048

fixed timer formatting

---

Master Project/Assets/Enums/IngredientType.cs
Master Project/Assets/Scenes/Dialogue/Scripts/DialogueManager.cs
Master Project/Assets/Scenes/Microwave/Microwave_Goldberg.unity
Master Project/Assets/Scenes/Microwave/Scripts/Microwave.cs
Master Project/Assets/Scenes/Microwave/Scripts/MicrowaveAnimationScript.cs
Master Project/Assets/Scenes/Microwave/Scripts/MicrowaveScorekeeper.cs
Master Project/Assets/Scenes/Microwave/Scripts/MicrowaveScorekeeper.cs.meta
Master Project/Assets/Scenes/Microwave/Scripts/MicrowaveSpriteScript.cs
Master Project/Assets/Scenes/Microwave/Scripts/MicrowaveTimerScript.cs
Master Project/Assets/Scenes/Microwave/Scripts/tutorialScript.cs

added scorekeeping and added microwave namespace @noahwillcrow @gmarino2048

Added scorekeeping

---

Master Project/Assets/Scenes/Shaking/Shaking Scripts/ScorekeeperBehavior.cs

Added scoring line to shaking @noahwillcrow @gmarino2048

Added Scoring to Shaking

---

Art/Sound/Digital SFX/Correct Ingredient.mp3
Art/Sound/Digital SFX/Enter Diner.mp3
Art/Sound/Digital SFX/Manager Meter Critical LowerPitch.mp3
Art/Sound/Digital SFX/Manager Meter Critical.mp3
Art/Sound/Digital SFX/Manager Meter Goes Down.mp3
Art/Sound/Digital SFX/Manager Meter Goes Up.mp3
Art/Sound/Digital SFX/Manager Meter Hits 0.mp3
Art/Sound/Digital SFX/Menu Navigation.mp3
Art/Sound/Digital SFX/Menu Selection.mp3
Art/Sound/Digital SFX/Monster Approval.mp3
Art/Sound/Digital SFX/Monster DisApproval (Fight).mp3
Art/Sound/Digital SFX/Monster Game Over.mp3
Art/Sound/Digital SFX/Monster Misses.mp3
Art/Sound/Digital SFX/Monster is Hit LowerPitch.mp3
Art/Sound/Digital SFX/Monster is Hit.mp3
Art/Sound/Digital SFX/Order Up.mp3
Art/Sound/Digital SFX/Player HP Goes Down.mp3
Art/Sound/Digital SFX/Player HP Going Up.mp3
Art/Sound/Digital SFX/Player HP Hits 0.mp3
Art/Sound/Digital SFX/Player HP Low.mp3
Art/Sound/Digital SFX/Player Hit.mp3
Art/Sound/Digital SFX/Wrong Ingredient.mp3

All non-acoustic sound effects including Game Over Jingle

Digital SFX

---

Art/Food_Assets/Editor_Files/Mazur_Phillips_Davis_Food_Layout_3.psd
Art/Food_Assets/PNGs/Mazur_MixedEggs_1.png
Art/Food_Assets/PNGs/Mazur_MixingBowl_1.png
Art/Food_Assets/PNGs/Mazur_MixingEggs_1.png
Art/Food_Assets/PNGs/Mazur_WeirdSteak_Cooked_1.png
Art/Food_Assets/PNGs/Mazur_WeirdSteak_Cooked_2.png
Art/Food_Assets/PNGs/Mazur_WeirdSteak_Cooked_3.png
Art/Food_Assets/PNGs/Mazur_WeirdSteak_PartialCooked_1.png
Art/UXUI/PNG/MainMenuAssets/Mazur_Credits_1.png
Art/UXUI/PNG/MainMenuAssets/Mazur_Credits_BackButton_1.png
Art/UXUI/PNG/MainMenuAssets/Mazur_Instructions_1.png
Art/UXUI/PNG/MainMenuAssets/Mazur_Instructions_BackButton_1.png
Art/UXUI/PNG/MainMenuAssets/Mazur_MainMenu_1.png
Art/UXUI/PNG/MainMenuAssets/Mazur_MainMenu_Background_1.png
Art/UXUI/PNG/MainMenuAssets/Mazur_MainMenu_CreditsButton_1.png
Art/UXUI/PNG/MainMenuAssets/Mazur_MainMenu_InstructionsButton_1.png
Art/UXUI/PNG/MainMenuAssets/Mazur_MainMenu_OptionsButton_1.png
Art/UXUI/PNG/MainMenuAssets/Mazur_MainMenu_QuitButton_1.png
Art/UXUI/PNG/MainMenuAssets/Mazur_MainMenu_StartButton_1.png
Art/UXUI/PNG/MainMenuAssets/Mazur_Options_1.png
Art/UXUI/PNG/MainMenuAssets/Mazur_Options_BackButton_1.png
Art/UXUI/PNG/MainMenuAssets/Mazur_Options_EggSlider_1.png
Art/UXUI/PNG/MainMenuAssets/Mazur_Options_PancakeSlider_1.png
Art/UXUI/PNG/MainMenuAssets/Mazur_Options_QaveLogoSlider_1.png
Art/UXUI/PNG/MainMenuAssets/Mazur_Options_SoundSlider_1.png

Individual PNGs of all the menu assets
Cooked and partially cooked weird steak sprites for grilling mini game
Mixed,unmixed egg, and bowl sprites for mixing mini game

Mazur menu pngs and food assets

---

Art/Monsters/Editor_Files/Phillips_MonsterLineart_2.psd

Added New PSD for Monster Lineart

---

Art/Food_Assets/Editor_Files/Mazur_Grill_Food_1.psd
Art/Food_Assets/PNGs/Mazur_Grill_BeefCooked_1.png
Art/Food_Assets/PNGs/Mazur_Grill_BeefPartialCooked_1.png
Art/Food_Assets/PNGs/Mazur_Grill_BeefUncooked_1.png
Art/Tool_Assets/PNGs/Mazur_Grill_Spatula_1.png
Art/UXUI/Illustrator/Mazur_Dialogue_UI_3.ai
Art/UXUI/Illustrator/Mazur_MainMenu_UI_5.ai
Art/UXUI/PNG/Mazur_Dialogue_NameUI_1.png
Art/UXUI/PNG/Mazur_Dialogue_NameUI_Cerberus_1.png
Art/UXUI/PNG/Mazur_Dialogue_NameUI_Nessie_1.png
Art/UXUI/PNG/Mazur_Dialogue_NameUI_Redacted_1.png

Grill: Spatula, Beef, Beef Partial Cooked, Beef Cooked
Dialogue Name UI and Main Menu visual update

Miscellaneous Upload

---

Art/Tool_Assets/PNGs/Phillips_Knife_3.png

Its a Knife

---

Art/Food_Assets/PNGs/Mazur_Grill_BeefBurned_1.png
Art/Food_Assets/PNGs/Mazur_Grill_BeefOverCooked_1.png
Art/Food_Assets/PNGs/Mazur_WeirdSteak_Burnt_1.png
Art/Food_Assets/PNGs/Mazur_WeirdSteak_Cooked_4.png
Art/Food_Assets/PNGs/Mazur_WeirdSteak_OverCooked_1.png

Weird Steak: Cooked redesign, OverCooked, and Burned
Beef: Overcooked and Burned

Mazur Grill Meat Upload

---

Art/Monsters/Editor_Files/Pizarro-Ruiz_MonsterColorPalette_1.psd
Art/Monsters/Editor_Files/Pizarro-Ruiz_MonsterLineart_3.psd
Art/Monsters/PNGs/Combat/Cerberus/Pizarro-Ruiz_CombatCerberusAttack_1.png
Art/Monsters/PNGs/Combat/Cerberus/Pizarro-Ruiz_CombatCerberusDamaged_1.png
Art/Monsters/PNGs/Combat/Cerberus/Pizarro-Ruiz_CombatCerberusNeutral_1.png
Art/Monsters/PNGs/Combat/Nessie/Pizarro-Ruiz_CombatNessieAttack_1.png
Art/Monsters/PNGs/Combat/Nessie/Pizarro-Ruiz_CombatNessieDamaged_1.png
Art/Monsters/PNGs/Combat/Nessie/Pizarro-Ruiz_CombatNessieNeutral_1.png
Art/Monsters/PNGs/Combat/Redacted/Pizarro-Ruiz_CombatRedactedAttack_1.png
Art/Monsters/PNGs/Combat/Redacted/Pizarro-Ruiz_CombatRedactedDamaged_1.png
Art/Monsters/PNGs/Combat/Redacted/Pizarro-Ruiz_CombatRedactedNeutral_1.png
Art/Monsters/PNGs/Dialogue/Cerberus/Pizarro-Ruiz_DialogueCerberusBad_1.png
Art/Monsters/PNGs/Dialogue/Cerberus/Pizarro-Ruiz_DialogueCerberusGood_1.png
Art/Monsters/PNGs/Dialogue/Cerberus/Pizarro-Ruiz_DialogueCerberusNeutral_1.png
Art/Monsters/PNGs/Dialogue/Nessie/Pizarro-Ruiz_DialogueNessieBad_1.png
Art/Monsters/PNGs/Dialogue/Nessie/Pizarro-Ruiz_DialogueNessieGood_1.png
Art/Monsters/PNGs/Dialogue/Nessie/Pizarro-Ruiz_DialogueNessieNeutral_1.png
Art/Monsters/PNGs/Dialogue/Redacted/Pizarro-Ruiz_DialogueRedactedBad_1.png
Art/Monsters/PNGs/Dialogue/Redacted/Pizarro-Ruiz_DialogueRedactedGood_1.png
Art/Monsters/PNGs/Dialogue/Redacted/Pizarro-Ruiz_DialogueRedactedNeutral_1.png

release me. close #187  close #188  close #218

Pizarro ruiz character colors

---

Art/UXUI/Illustrator/Mazur_Battle_UI_3.ai
Art/UXUI/Illustrator/Mazur_PauseMenu_2.ai
Art/UXUI/Illustrator/Mazur_Tutorial_UI_3.ai
Art/UXUI/PNG/Mazur_Battle_UI_HealthBar_1.png
Art/UXUI/PNG/Mazur_Battle_UI_HealthBar_2.png
Art/UXUI/PNG/Mazur_Battle_UI_Healthbars_1.png
Art/UXUI/PNG/Mazur_Battle_UI_Healthbars_2.png
Art/UXUI/PNG/Mazur_Battle_UI_ManagerMeterRed_1.png
Art/UXUI/PNG/Mazur_Battle_UI_ManagerMeter_1.png
Art/UXUI/PNG/Mazur_Battle_UI_ManagerMeter_2.png
Art/UXUI/PNG/PauseMenu/Mazur_PauseMenu_4.png
Art/UXUI/PNG/Tutorial/Mazur_ScoreBar_1.png
Art/UXUI/PNG/Tutorial/Mazur_Tutorial_Background_1.png
Art/UXUI/PNG/Tutorial/Mazur_Tutorial_FullScreen_Background_1.png
Art/UXUI/PNG/Tutorial/Mazur_Tutorial_NextButton_1.png
Art/UXUI/PNG/Tutorial/Mazur_Tutorial_NextButton_2.png

Sorry this took so long and is so late
A few variations of the health bar and manager meter
An updated pause menu, repositioned the scroll bar
Backgrounds for the cooking tutorials and scoring as well as next buttons

Health Bars, Tutorial Backgrounds, and updated Pause menu

---

Art/Backgrounds/PNGs/Bright_Game Over Screen.png
Art/Bright_Assets/Bright_GameOverScreen2.png.png
Art/Bright_Assets/Game Over Screen.png

Pushing and Pulling branches is my passion, cant you tell?....

Game Over Screen

---

Art/Sound/Monster Date Aquired.mp3

Update Art/Sound/Monster Date Aquired.mp3

---

Master Project/Assets/Scenes/Grill/Assets/Images.meta
Master Project/Assets/Scenes/Grill/Assets/Prefabs.meta
Master Project/Assets/Scenes/Grill/Assets/Sprite Sheets/Flame Start.meta
Master Project/Assets/Scenes/Main Menu/Main Menu.unity

fixed the tiny text issue @gmarino2048

adjusted main menu size

---

Art/UXUI/PNG/Pizarro-Ruiz_IngredientMarker_1.png
Art/UXUI/PNG/Pizarro-Ruiz_LogoSketches_1.png
Art/UXUI/PNG/Pizarro-Ruiz_RedX_1.png
Art/UXUI/PSD/Pizarro-Ruiz_LogoSketches_1.psd

We got logos and some other assets the programmers asked for close #212

Pizarro ruiz logos

---

Master Project/Assets/Scenes/Grill/Assets/Animation Sprites/Flame Start.meta
Master Project/Assets/Scenes/Grill/Grill.unity

I added a little catchphrase to the tutorial so that it's a little cuter and it's not just the animation.

Grill marino

---

Art/Food_Assets/PNGs/Bone_1.png
Art/Food_Assets/PNGs/CutintoBone_1.png
Art/Food_Assets/PNGs/CutintoPepper_1.png
Art/Food_Assets/PNGs/PepperCut_1.png
Art/Food_Assets/PNGs/Pepper_1.png

I fixed my shit for the bone and pepper sprites

---

Art/Tool_Assets/PNGs/Phillips_Knife_4.png

Ill use a Knife

---

Art/Fonts/OCRAStd.otf
Art/Fonts/ocrastd.png
Art/Fonts/sharefonts.net.txt

Microwave Fonttttt

---

Master Project/Assets/Scenes/Grill/Assets/Animation Sprites/Flame Start.meta
Master Project/Assets/Scenes/Ingredients/Art/Pizarro-Ruiz_IngredientMarker_1.png
Master Project/Assets/Scenes/Ingredients/Art/Pizarro-Ruiz_IngredientMarker_1.png.meta
Master Project/Assets/Scenes/Ingredients/Art/Pizarro-Ruiz_RedX_1.png
Master Project/Assets/Scenes/Ingredients/Art/Pizarro-Ruiz_RedX_1.png.meta
Master Project/Assets/Scenes/Ingredients/IngredientsScene.unity
Master Project/Assets/Scenes/Ingredients/Prefab/IngredientChoice.prefab
Master Project/Assets/Scenes/Ingredients/Scripts/DragIngredient.cs
Master Project/Assets/Scenes/Ingredients/Scripts/IngredientChoiceLocation.cs
Master Project/Assets/Scenes/Ingredients/Scripts/IngredientText.cs
Master Project/Assets/Scenes/Ingredients/Scripts/IngredientText.cs.meta
Master Project/Assets/Scenes/Ingredients/Scripts/IngredientsManager.cs
Master Project/Assets/Scripts/Monsters/MonsterData.cs

ingredient scene point/score deduction implemented

ingredient scene point/score deduction along with labels for ingredients

---

Master Project/Assets/Scenes/Shaking/Scripts/ScorekeeperBehavior.cs
Master Project/Assets/Scenes/Shaking/Scripts/UIController.cs
Master Project/Assets/Scenes/Shaking/Shaking.unity

The usual, but for shaking this time

Shaking Tutorial/etc updates

---

Master Project/Assets/Scenes/Chopping/Chopping.unity
Master Project/Assets/Scenes/Chopping/Scripts/ScorekeeperBehavior.cs
Master Project/Assets/Scenes/Chopping/Scripts/UIManager.cs

Chopping Alterations

---

Master Project/Assets/Scenes/Combat/CombatScene.unity
Master Project/Assets/Scenes/Combat/Comfortaa-Regular.ttf.meta
Master Project/Assets/Scenes/Combat/Mazur_Tutorial_Mouse_Icon.png
Master Project/Assets/Scenes/Combat/Mazur_Tutorial_Mouse_Icon.png.meta
Master Project/Assets/Scenes/Combat/Qi_Animation/Cerberus_Attack.anim
Master Project/Assets/Scenes/Combat/Qi_Animation/Cerberus_Damaged.anim
Master Project/Assets/Scenes/Combat/Qi_Animation/Cerberus_Idle.anim
Master Project/Assets/Scenes/Combat/Qi_Animation/Nessie_Attack.anim
Master Project/Assets/Scenes/Combat/Qi_Animation/Nessie_Damaged.anim
Master Project/Assets/Scenes/Combat/Qi_Animation/Nessie_Idle.anim
Master Project/Assets/Scenes/Combat/Qi_Animation/REDACTED_Attack.anim
Master Project/Assets/Scenes/Combat/Qi_Animation/REDACTED_Damaged.anim
Master Project/Assets/Scenes/Combat/Qi_Animation/REDACTED_Idle.anim
Master Project/Assets/Scenes/Combat/Qi_Scripts/AudioController.cs
Master Project/Assets/Scenes/Combat/Qi_Scripts/HealthBar.cs
Master Project/Assets/Scenes/Combat/Qi_Scripts/ManagerBar.cs
Master Project/Assets/Scenes/Combat/Qi_Scripts/MonsterAction.cs
Master Project/Assets/Scenes/Combat/Qi_Scripts/MonsterNames.cs
Master Project/Assets/Scenes/Combat/Qi_Scripts/MonsterNames.cs.meta
Master Project/ProjectSettings/ProjectSettings.asset

Now everything is in its real size.
Add mouse sprite

CombatScene Update

---

Art/Monsters/Editor_Files/Pizarro-Ruiz_NessieDate_1.psd
Art/Monsters/PNGs/Pizarro-Ruiz_NessieDate_1.png

Nessie date art woohoo! close #288

Nessie Date

---

Master Project/Assets/Scenes/Grill/Assets/Animation Sprites/Flame Start.meta
Master Project/Assets/Scenes/Microwave/Microwaving.unity
Master Project/Assets/Scenes/Microwave/Scripts/AssetManager.cs
Master Project/Assets/Scenes/Microwave/Scripts/AssetManager.cs.meta

Microwave marino

---

Art/Sound/Monster SFX 2/Can Banging (Long Sporadic).mp3
Art/Sound/Monster SFX 2/Egg Beater.mp3
Art/Sound/Monster SFX 2/Fire.mp3
Art/Sound/Monster SFX 2/Goo Bubbling (Faster).mp3
Art/Sound/Monster SFX 2/Goo Bubbling (In Microwave).mp3
Art/Sound/Monster SFX 2/Goo Bubbling.mp3
Art/Sound/Monster SFX 2/Goo Stir.mp3
Art/Sound/Monster SFX 2/Ice Cream Scoop.mp3
Art/Sound/Monster SFX 2/Ice Cream Stir.mp3
Art/Sound/Monster SFX 2/Meat Slap.mp3
Art/Sound/Monster SFX 2/Power Switch.mp3
Art/Sound/Monster SFX 2/Running Water (Nessie).mp3
Art/Sound/Monster SFX 2/Souls of the Cooked.mp3
Art/Sound/Monster SFX 2/Spooky Void Burst No Kick.mp3
Art/Sound/Monster SFX 2/Spooky Void Burst.mp3
Art/Sound/Monster SFX 2/Spooky Void Long.mp3
Art/Sound/Monster SFX 2/Spooky Void Short.mp3
Art/Sound/Monster SFX 2/Tear Through Reality.mp3
Art/Sound/Monster SFX 2/Telephone Ringing.mp3

Let me know if you want any of them different or edited

Final Monster Sounds

---

Art/UXUI/PNG/MainMenuAssets/Mazur_Credits_2.png
Art/UXUI/PNG/MainMenuAssets/Mazur_Instructions_BackButton_2.png
Art/UXUI/PNG/MainMenuAssets/Mazur_Instructions_NextButton_1.png
Art/UXUI/PNG/MainMenuAssets/Mazur_Instructions_Page1_1.png
Art/UXUI/PNG/MainMenuAssets/Mazur_Instructions_Page2_1.png
Art/UXUI/PNG/MainMenuAssets/Mazur_Options_2.png
Art/UXUI/PNG/MainMenuAssets/Mazur_Options_SampleText_1.png
Art/UXUI/PNG/MainMenuAssets/Mazur_Options_SizeSlider_1.png
Art/UXUI/PNG/MainMenuAssets/Mazur_Options_SizeSlider_Text_1.png
Art/UXUI/PNG/MainMenuAssets/Mazur_Options_SpeedSlider_1.png
Art/UXUI/PNG/MainMenuAssets/Mazur_Options_SpeedSlider_Text_1.png
Art/UXUI/PNG/MainMenuAssets/Mazur_Options_TextSizeAdjustment_1.png
Art/UXUI/PNG/MainMenuAssets/Mazur_Options_TextSlider_1.png
Art/UXUI/PNG/MainMenuAssets/Mazur_Options_TextSpeedAdjustment_1.png
Art/UXUI/PNG/Mazur_GameOver_ReturnButton_1.png
Art/UXUI/PNG/Mazur_NameSelection_EnterButton_1.png

Buttons:
Enter button for the name selection
Return to main menu button for the game over menu
Menus:
Updated credits
Adjusted instructions split between two pages
Additional text adjustment options on the options menu

Buttons and Menu adjustments

---

Art/UXUI/PNG/DateScene/Mazur_PauseMenu_Background_1.png
Art/UXUI/PNG/DateScene/Phillips_DateNumber_Cerberus_1.png
Art/UXUI/PNG/DateScene/Phillips_DateNumber_Nessie_1.png
Art/UXUI/PNG/DateScene/Phillips_DateNumber_REDACTED_1.png

The background is the same as the monologue scene but with the date number overlaid on top.

Final Date Scene Numbers

---

Art/UXUI/PNG/Logos/Pizarro-Ruiz_LogoSquare_1.png
Art/UXUI/PNG/Logos/Pizarro-Ruiz_LogoSquare_2.png

Square Logos

---

Master Project/Assets/Scenes/Main Menu/Main Menu.unity
Master Project/Assets/Scenes/Main Menu/Scripts/PlayOnclick.cs
Master Project/Assets/Scenes/Main Menu/Sprites/Mazur_Credits_2.png
Master Project/Assets/Scenes/Main Menu/Sprites/Mazur_Credits_2.png.meta
Master Project/Assets/Scenes/Main Menu/Sprites/Mazur_Instructions_BackButton_2.png
Master Project/Assets/Scenes/Main Menu/Sprites/Mazur_Instructions_BackButton_2.png.meta
Master Project/Assets/Scenes/Main Menu/Sprites/Mazur_Instructions_NextButton_1.png
Master Project/Assets/Scenes/Main Menu/Sprites/Mazur_Instructions_NextButton_1.png.meta
Master Project/Assets/Scenes/Main Menu/Sprites/Mazur_Instructions_Page1_1.png
Master Project/Assets/Scenes/Main Menu/Sprites/Mazur_Instructions_Page1_1.png.meta
Master Project/Assets/Scenes/Main Menu/Sprites/Mazur_Instructions_Page2_1.png
Master Project/Assets/Scenes/Main Menu/Sprites/Mazur_Instructions_Page2_1.png.meta
Master Project/Assets/Scenes/Main Menu/Sprites/Mazur_MainMenu_Background_2.png
Master Project/Assets/Scenes/Main Menu/Sprites/Mazur_MainMenu_Background_2.png.meta
Master Project/Assets/Scenes/Main Menu/Sprites/Mazur_Options_2.png
Master Project/Assets/Scenes/Main Menu/Sprites/Mazur_Options_2.png.meta
Master Project/Assets/Scenes/Main Menu/Sprites/Mazur_Options_SampleText_1.png
Master Project/Assets/Scenes/Main Menu/Sprites/Mazur_Options_SampleText_1.png.meta
Master Project/Assets/Scenes/Main Menu/Sprites/Mazur_Options_SizeSlider_1.png
Master Project/Assets/Scenes/Main Menu/Sprites/Mazur_Options_SizeSlider_1.png.meta
Master Project/Assets/Scenes/Main Menu/Sprites/Mazur_Options_SizeSlider_Text_1.png
Master Project/Assets/Scenes/Main Menu/Sprites/Mazur_Options_SizeSlider_Text_1.png.meta
Master Project/Assets/Scenes/Main Menu/Sprites/Mazur_Options_SoundSlider_2.png
Master Project/Assets/Scenes/Main Menu/Sprites/Mazur_Options_SoundSlider_2.png.meta
Master Project/Assets/Scenes/Main Menu/Sprites/Mazur_Options_SpeedSlider_1.png
Master Project/Assets/Scenes/Main Menu/Sprites/Mazur_Options_SpeedSlider_1.png.meta
Master Project/Assets/Scenes/Main Menu/Sprites/Mazur_Options_SpeedSlider_Text_1.png
Master Project/Assets/Scenes/Main Menu/Sprites/Mazur_Options_SpeedSlider_Text_1.png.meta
Master Project/Assets/Scenes/Main Menu/Sprites/Mazur_Options_TextSlider_1.png
Master Project/Assets/Scenes/Main Menu/Sprites/Mazur_Options_TextSlider_1.png.meta

added 2 pages of instructions, updated assets, and updated options for text scroll speeds
Jonathan and Bailey did this

fixed options menu, and updated mainmenu assets

---

Master Project/Assets/Scenes/Monologue/Scripts/MonologueSceneManager.cs

added frames per character to monologue

---

Master Project/Assets/Scenes/FinalChoice/Scripts/FinalChoiceSceneManager.cs

Change name from "Redacted" to "[REDACTED]"

FinalChoice Scene Bug Fix

---

Master Project/Assets/StreamingAssets/Data/Monsters.xml

fixed bugs that beg option does nothing

Combat Scene Update

---

Master Project/Assets/Scenes/Main Menu/Main Menu.unity

further fixes for correct scaling

added main menu fixes

---

Master Project/Assets/Scenes/Main Menu/Main Menu.unity
Master Project/Assets/Scenes/Main Menu/Sprites/Instructions.meta

I redid the menu because it was set to 16:10 locally and there was much ado about nothing

Menu adjustments mertz
